/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CrearPerfil extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearPerfil.class.getName());
    private String fotoSeleccionada = "foto1";

    private javax.swing.ImageIcon icono1 = new javax.swing.ImageIcon(getClass().getResource("/juego/foto1.png"));
    private javax.swing.ImageIcon icono2 = new javax.swing.ImageIcon(getClass().getResource("/juego/foto2.png"));
    private javax.swing.ImageIcon icono3 = new javax.swing.ImageIcon(getClass().getResource("/juego/foto3.png"));
    private javax.swing.ImageIcon icono4 = new javax.swing.ImageIcon(getClass().getResource("/juego/foto4.png"));
    private javax.swing.ImageIcon icono5 = new javax.swing.ImageIcon(getClass().getResource("/juego/foto4.png"));

    /**
     * Creates new form CrearPerfil
     */
    public CrearPerfil() {
        initComponents();

        this.getContentPane().setLayout(null);
        jDesktopPane1.setSize(493, 347);
        this.getContentPane().setComponentZOrder(jDesktopPane1, 0);

        if (aviso != null) {
            aviso.setText("");
        }
        jDesktopPane1.setVisible(false);

        this.setSize(830, 508);
        this.setLocationRelativeTo(null);
        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
    }

    public void actualizarInterfazIdioma() {
        if (Idioma.isEspanol()) {
            doneEsp.setVisible(true);
            done.setVisible(false);
            jLabel1.setVisible(false);
            jLabelEsp.setVisible(true);
            fotoDeperfilEsp.setVisible(true);
            fotoDeperfil.setVisible(false);
            backEsp.setVisible(true);
            back.setVisible(false);
            perfilEspanol.setVisible(true);
            perfilIngles.setVisible(false);
            doneEspanol.setVisible(true);
            doneIngles.setVisible(false);
            jRadioButton1.setText("Foto 1");
            jRadioButton2.setText("Foto 2");
            jRadioButton3.setText("Foto 3");
            jRadioButton4.setText("Foto 4");
            jRadioButton5.setText("Foto 5");

        } else {
            done.setVisible(true);
            doneEsp.setVisible(false);
            jLabel1.setVisible(true);
            jLabelEsp.setVisible(false);
            fotoDeperfil.setVisible(true);
            fotoDeperfilEsp.setVisible(false);
            back.setVisible(true);
            backEsp.setVisible(false);
            perfilEspanol.setVisible(false);
            perfilIngles.setVisible(true);
            doneEspanol.setVisible(false);
            doneIngles.setVisible(true);
            jRadioButton1.setText("Photo 1");
            jRadioButton2.setText("Photo 2");
            jRadioButton3.setText("Photo 3");
            jRadioButton4.setText("Photo 4");
            jRadioButton5.setText("Photo 5");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nombre = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        fotoDeperfilEsp = new javax.swing.JButton();
        fotoDeperfil = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        backEsp = new javax.swing.JButton();
        doneEsp = new javax.swing.JButton();
        fotoperfil = new javax.swing.JButton();
        verPass = new javax.swing.JCheckBox();
        jLabelEsp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        doneEspanol = new javax.swing.JButton();
        doneIngles = new javax.swing.JButton();
        perfilIngles = new javax.swing.JLabel();
        perfilEspanol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nombre.addActionListener(this::nombreActionPerformed);
        getContentPane().add(nombre);
        nombre.setBounds(320, 90, 180, 30);

        username.addActionListener(this::usernameActionPerformed);
        getContentPane().add(username);
        username.setBounds(320, 180, 180, 30);

        password.addActionListener(this::passwordActionPerformed);
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(320, 260, 180, 30);

        fotoDeperfilEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/pfpesp.png"))); // NOI18N
        fotoDeperfilEsp.addActionListener(this::fotoDeperfilEspActionPerformed);
        getContentPane().add(fotoDeperfilEsp);
        fotoDeperfilEsp.setBounds(10, 10, 150, 30);

        fotoDeperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/pfp.png"))); // NOI18N
        fotoDeperfil.addActionListener(this::fotoDeperfilActionPerformed);
        getContentPane().add(fotoDeperfil);
        fotoDeperfil.setBounds(10, 10, 110, 30);

        aviso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 255, 255));
        aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aviso.setText("aviso");
        getContentPane().add(aviso);
        aviso.setBounds(240, 320, 340, 90);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(510, 420, 90, 30);

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/7.png"))); // NOI18N
        done.addActionListener(this::doneActionPerformed);
        getContentPane().add(done);
        done.setBounds(270, 420, 90, 30);

        backEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11esp.png"))); // NOI18N
        backEsp.addActionListener(this::backEspActionPerformed);
        getContentPane().add(backEsp);
        backEsp.setBounds(510, 420, 90, 30);

        doneEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/esp4.png"))); // NOI18N
        doneEsp.addActionListener(this::doneEspActionPerformed);
        getContentPane().add(doneEsp);
        doneEsp.setBounds(270, 420, 90, 30);

        fotoperfil.addActionListener(this::fotoperfilActionPerformed);
        getContentPane().add(fotoperfil);
        fotoperfil.setBounds(720, 30, 80, 80);

        verPass.setBackground(new java.awt.Color(255, 255, 255));
        verPass.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        verPass.setForeground(new java.awt.Color(0, 0, 0));
        verPass.setText("Ver contraseña");
        verPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        verPass.addActionListener(this::verPassActionPerformed);
        getContentPane().add(verPass);
        verPass.setBounds(350, 290, 120, 20);

        jLabelEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/usesp2.png"))); // NOI18N
        getContentPane().add(jLabelEsp);
        jLabelEsp.setBounds(0, 0, 830, 501);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/using2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 501);

        jDesktopPane1.setOpaque(false);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Foto 5");
        jRadioButton5.addActionListener(this::jRadioButton5ActionPerformed);
        jDesktopPane1.add(jRadioButton5);
        jRadioButton5.setBounds(250, 240, 140, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Foto 4");
        jRadioButton4.addActionListener(this::jRadioButton4ActionPerformed);
        jDesktopPane1.add(jRadioButton4);
        jRadioButton4.setBounds(120, 240, 130, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Foto 3");
        jRadioButton3.addActionListener(this::jRadioButton3ActionPerformed);
        jDesktopPane1.add(jRadioButton3);
        jRadioButton3.setBounds(320, 140, 130, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Foto 2");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);
        jDesktopPane1.add(jRadioButton2);
        jRadioButton2.setBounds(180, 140, 130, 21);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Foto 1");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
        jDesktopPane1.add(jRadioButton1);
        jRadioButton1.setBounds(60, 140, 140, 21);

        doneEspanol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/esp4.png"))); // NOI18N
        doneEspanol.addActionListener(this::doneEspanolActionPerformed);
        jDesktopPane1.add(doneEspanol);
        doneEspanol.setBounds(180, 260, 90, 30);

        doneIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/7.png"))); // NOI18N
        doneIngles.addActionListener(this::doneInglesActionPerformed);
        jDesktopPane1.add(doneIngles);
        doneIngles.setBounds(180, 260, 90, 30);

        perfilIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/profile pic.png"))); // NOI18N
        jDesktopPane1.add(perfilIngles);
        perfilIngles.setBounds(0, 0, 480, 310);

        perfilEspanol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/foto de perfil.png"))); // NOI18N
        jDesktopPane1.add(perfilEspanol);
        perfilEspanol.setBounds(0, 0, 470, 290);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(260, 10, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        String user = username.getText().trim();
        String passw = new String(password.getPassword()).trim();

        if (user.isEmpty() || passw.isEmpty()) {
            aviso.setText("Complete todos los campos.");
            return;
        }

        if (!passw.matches(".*[A-Z].*") || !passw.matches(".*[a-z].*")
                || !passw.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\",.<>/?\\\\|].*") || !passw.matches(".*\\d.*")) {
            return;
        }

        PersistenciaJugador persistencia = new PersistenciaJugador();
        if (persistencia.existeJugador(user)) {
            aviso.setText("El usuario ya existe en el sistema.");
            return;
        }

        aviso.setText("");

        ImageIcon foto= (ImageIcon) fotoperfil.getIcon();
        Jugador jugador = new Jugador(user, user, passw, foto);

        persistencia.guardarJugador(jugador);

        jDesktopPane1.setVisible(false);
        username.setEnabled(true);
        password.setEnabled(true);

        this.dispose();
        UsuarioGuardado usuarioGuardado = new UsuarioGuardado();
        usuarioGuardado.setVisible(true);
        new InicioJuego().setVisible(true);
    }//GEN-LAST:event_doneActionPerformed

    private void doneEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEspActionPerformed
        // TODO add your handling code here:
        String name= nombre.getText().trim();
        String user = username.getText().trim();
        String passw = new String(password.getPassword()).trim();

        if (user.isEmpty() || passw.isEmpty()) {
            aviso.setText("Complete todos los campos.");
            return;
        }

        if (!passw.matches(".*[A-Z].*") || !passw.matches(".*[a-z].*")
                || !passw.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\",.<>/?\\\\|].*") || !passw.matches(".*\\d.*")) {
            return;
        }

        PersistenciaJugador persistencia = new PersistenciaJugador();
        if (persistencia.existeJugador(user)) {
            aviso.setText("El usuario ya existe en el sistema.");
            return;
        }

        aviso.setText("");
        
        ImageIcon foto= (ImageIcon) fotoperfil.getIcon();
        Jugador jugador = new Jugador(user, name, passw, foto);

        persistencia.guardarJugador(jugador);

        jDesktopPane1.setVisible(false);
        username.setEnabled(true);
        password.setEnabled(true);

        this.dispose();
        UsuarioGuardado usuarioGuardado = new UsuarioGuardado();
        usuarioGuardado.setVisible(true);
        new InicioJuego().setVisible(true);
    }//GEN-LAST:event_doneEspActionPerformed

    private void verPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPassActionPerformed
        // TODO add your handling code here: 695, 490
        if (verPass.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('•');
        }
    }//GEN-LAST:event_verPassActionPerformed

    private void fotoDeperfilEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoDeperfilEspActionPerformed
        // TODO add your handling code here:
        int anchoPanel = 450;
        int altoPanel = 295;
        int x = (this.getWidth() - anchoPanel) / 2;
        int y = (this.getHeight() - altoPanel) / 2;

        jDesktopPane1.setBounds(x, y, anchoPanel, altoPanel);

        jDesktopPane1.setVisible(true);

        this.getContentPane().repaint();
        this.getContentPane().revalidate();

        username.setEnabled(false);
        password.setEnabled(false);
    }//GEN-LAST:event_fotoDeperfilEspActionPerformed

    private void fotoDeperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoDeperfilActionPerformed
        // TODO add your handling code here:
        int anchoPanel = 450;
        int altoPanel = 295;
        int x = (this.getWidth() - anchoPanel) / 2;
        int y = (this.getHeight() - altoPanel) / 2;

        jDesktopPane1.setBounds(x, y, anchoPanel, altoPanel);

        jDesktopPane1.setVisible(true);

        this.getContentPane().repaint();
        this.getContentPane().revalidate();

        username.setEnabled(false);
        password.setEnabled(false);
    }//GEN-LAST:event_fotoDeperfilActionPerformed

    private void doneInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneInglesActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.setVisible(false);
        username.setEnabled(true);
        password.setEnabled(true);
    }//GEN-LAST:event_doneInglesActionPerformed

    private void doneEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEspanolActionPerformed
        // TODO add your handling code here:
        if (fotoSeleccionada.equals("foto1")) {
            fotoperfil.setIcon(icono1);
        } else if (fotoSeleccionada.equals("foto2")) {
            fotoperfil.setIcon(icono2);
        } else if (fotoSeleccionada.equals("foto3")) {
            fotoperfil.setIcon(icono3);
        } else if (fotoSeleccionada.equals("foto4")) {
            fotoperfil.setIcon(icono4);
        } else if (fotoSeleccionada.equals("foto5")) {
            fotoperfil.setIcon(icono5);
        }

        jDesktopPane1.setVisible(false);

        username.setEnabled(true);
        password.setEnabled(true);
    }//GEN-LAST:event_doneEspanolActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:]
        String passw = new String(password.getPassword()).trim();

        if (passw.isEmpty()) {
            aviso.setText("");
            return;
        }

        String errores = "";

        if (passw.length() <= 5) {
            errores += "- Falta mas de 5 caracteres<br>";
        }

        if (!passw.matches(".*[A-Z].*")) {
            errores += "- Falta mayuscula<br>";
        }
        if (!passw.matches(".*[a-z].*")) {
            errores += "- Falta minuscula<br>";
        }
        if (!passw.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\",.<>/?\\\\|].*")) {
            errores += "- Falta caracter especial<br>";
        }
        if (!passw.matches(".*\\d.*")) {
            errores += "- Falta numero<br>";
        }

        if (!errores.isEmpty()) {
            aviso.setText("<html><font color='red'>" + errores + "</font></html>");
        } else {
            aviso.setText("<html><font color='green'>¡Contraseña segura!</font></html>");
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        fotoSeleccionada = "foto1";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        fotoSeleccionada = "foto2";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        fotoSeleccionada = "foto3";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        fotoSeleccionada = "foto4";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        fotoSeleccionada = "foto5";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void fotoperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoperfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoperfilActionPerformed

    private void backEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEspActionPerformed
        // TODO add your handling code here:
        InicioJuego inicio = new InicioJuego();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_backEspActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        InicioJuego inicio = new InicioJuego();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearPerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JButton back;
    private javax.swing.JButton backEsp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton done;
    private javax.swing.JButton doneEsp;
    private javax.swing.JButton doneEspanol;
    private javax.swing.JButton doneIngles;
    private javax.swing.JButton fotoDeperfil;
    private javax.swing.JButton fotoDeperfilEsp;
    private javax.swing.JButton fotoperfil;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEsp;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel perfilEspanol;
    private javax.swing.JLabel perfilIngles;
    private javax.swing.JTextField username;
    private javax.swing.JCheckBox verPass;
    // End of variables declaration//GEN-END:variables
}
