/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class FotoDePerfil extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FotoDePerfil.class.getName());

    /**
     * Creates new form FotoDePerfil
     */
    public FotoDePerfil() {
        initComponents();
        this.setSize(695, 490);
        this.setLocationRelativeTo(null);

        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
    }

    public void actualizarInterfazIdioma() {
        if (Idioma.isEspanol()) {
            backEsp.setVisible(true);
            back.setVisible(false);
            done.setVisible(false);
            doneEsp.setVisible(true);
            jLabel1.setVisible(false);
            jLabelEsp.setVisible(true);
        } else {
            back.setVisible(true);
            backEsp.setVisible(false);
            done.setVisible(true);
            doneEsp.setVisible(false);
            jLabel1.setVisible(true);
            jLabelEsp.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        back = new javax.swing.JButton();
        backEsp = new javax.swing.JButton();
        done = new javax.swing.JButton();
        doneEsp = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEsp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(220, 400, 90, 30);

        backEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11esp.png"))); // NOI18N
        backEsp.addActionListener(this::backEspActionPerformed);
        getContentPane().add(backEsp);
        backEsp.setBounds(220, 400, 90, 30);

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/7.png"))); // NOI18N
        done.addActionListener(this::doneActionPerformed);
        getContentPane().add(done);
        done.setBounds(370, 400, 90, 30);

        doneEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/esp4.png"))); // NOI18N
        doneEsp.addActionListener(this::doneEspActionPerformed);
        getContentPane().add(doneEsp);
        doneEsp.setBounds(370, 400, 90, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(100, 220, 98, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 220, 98, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(470, 220, 98, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(190, 350, 98, 21);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(370, 350, 98, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/profile pic.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 460);

        jLabelEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/foto de perfil.png"))); // NOI18N
        getContentPane().add(jLabelEsp);
        jLabelEsp.setBounds(0, 0, 680, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEspActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backEspActionPerformed

    private void doneEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEspActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_doneEspActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
    }//GEN-LAST:event_backActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FotoDePerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backEsp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton done;
    private javax.swing.JButton doneEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEsp;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
