/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class Ganar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ganar.class.getName());

    /**
     * Creates new form Ganar
     */
    public Ganar() {
        initComponents();

        this.setSize(493, 347);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replay = new javax.swing.JButton();
        next = new javax.swing.JButton();
        niveles = new javax.swing.JButton();
        estrella1 = new javax.swing.JLabel();
        estrella3 = new javax.swing.JLabel();
        estrella2 = new javax.swing.JLabel();
        estrellaGris1 = new javax.swing.JLabel();
        estrellaGris2 = new javax.swing.JLabel();
        estrellaGris3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        replay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/12.png"))); // NOI18N
        replay.addActionListener(this::replayActionPerformed);
        getContentPane().add(replay);
        replay.setBounds(300, 220, 60, 40);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11.png"))); // NOI18N
        next.addActionListener(this::nextActionPerformed);
        getContentPane().add(next);
        next.setBounds(210, 220, 60, 40);

        niveles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/10.png"))); // NOI18N
        niveles.addActionListener(this::nivelesActionPerformed);
        getContentPane().add(niveles);
        niveles.setBounds(120, 220, 60, 40);

        estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrellita.png"))); // NOI18N
        getContentPane().add(estrella1);
        estrella1.setBounds(260, 110, 60, 60);

        estrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrellita.png"))); // NOI18N
        getContentPane().add(estrella3);
        estrella3.setBounds(200, 100, 60, 60);

        estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrellita.png"))); // NOI18N
        getContentPane().add(estrella2);
        estrella2.setBounds(140, 110, 60, 60);

        estrellaGris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrella gris.png"))); // NOI18N
        getContentPane().add(estrellaGris1);
        estrellaGris1.setBounds(250, 110, 70, 60);

        estrellaGris2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrella gris.png"))); // NOI18N
        getContentPane().add(estrellaGris2);
        estrellaGris2.setBounds(190, 100, 70, 60);

        estrellaGris3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/estrella gris.png"))); // NOI18N
        getContentPane().add(estrellaGris3);
        estrellaGris3.setBounds(130, 110, 70, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/9.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_nivelesActionPerformed

    private void replayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replayActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ganar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estrella1;
    private javax.swing.JLabel estrella2;
    private javax.swing.JLabel estrella3;
    private javax.swing.JLabel estrellaGris1;
    private javax.swing.JLabel estrellaGris2;
    private javax.swing.JLabel estrellaGris3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton next;
    private javax.swing.JButton niveles;
    private javax.swing.JButton replay;
    // End of variables declaration//GEN-END:variables
}
