/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Historial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Historial.class.getName());
    private Jugador jugador;

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();

        this.setSize(828, 505);
        this.setLocationRelativeTo(null);
        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
    }

    public Historial(Jugador jugador) {
        initComponents();

        this.setSize(828, 505);
        this.setLocationRelativeTo(null);
        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
        this.jugador = jugador;
        cargarHistorial();
    }

    public void actualizarInterfazIdioma() {
        if (Idioma.isEspanol()) {
            backEsp.setVisible(true);
            back.setVisible(false);
            jLabel1.setVisible(false);
            jLabelEsp.setVisible(true);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("FECHA");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("HORA");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("NIVEL");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("PUNTACION");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("TIEMPO JUGADO");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("VIDAS PERDIDAS");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("FALLOS");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("ESTADO");
        } else {
            back.setVisible(true);
            backEsp.setVisible(false);
            jLabel1.setVisible(true);
            jLabelEsp.setVisible(false);
            back.setVisible(true);
            backEsp.setVisible(false);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("DATE");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("TIME");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("LEVEL");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("SCORE");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("TIME PLAY");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("LIVES LOST");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("MISTAKES");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("STATUS");
        }
        jTable1.getTableHeader().repaint();
    }

    public void cargarHistorial() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (ResultadoPartida partida : jugador.getHistorialPartidas()) {
            String fecha = "";
            String hora = "";
            if (partida.getFechaHoraInicioPartida() != null) {
                fecha = partida.getFechaHoraInicioPartida().toLocalDate().toString();
                hora = partida.getFechaHoraInicioPartida().toLocalTime().toString();
            } else if (partida.getFecha() != null) {
                fecha = partida.getFecha().toLocalDate().toString();
                hora = partida.getFecha().toLocalTime().toString();
            }

            int nivel = partida.getNivelAlcanzado();
            int puntacion = partida.getCantidadEstrellasRecolectadas() * 100;
            String tiempo = String.format("%.0f seg", partida.getTiempoSegundos());
            int vidasPerdidas = 3 - partida.getVidasRestantes();
            int fallos = partida.getFallos();
            String estado = partida.isVictoria() ? "VICTORIA" : "DERROTA";
            modelo.addRow(new Object[]{fecha, hora, nivel, puntacion, tiempo, vidasPerdidas, fallos, estado});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        backEsp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEsp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FECHA", "HORA", "NIVEL", "PUNTUACION", "TIEMPO DE JUEGO", "VIDAS PERDIDAS", "FALLOS ESPECIFICOS", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setMinWidth(120);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(6).setMinWidth(120);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 750, 300);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(30, 30, 90, 30);

        backEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11esp.png"))); // NOI18N
        backEsp.addActionListener(this::backEspActionPerformed);
        getContentPane().add(backEsp);
        backEsp.setBounds(30, 30, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/historialing.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 510);

        jLabelEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/historialesp.png"))); // NOI18N
        getContentPane().add(jLabelEsp);
        jLabelEsp.setBounds(0, -10, 860, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Rankings rankings = new Rankings(jugador);
        rankings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEspActionPerformed
        // TODO add your handling code here:
        Rankings rankings = new Rankings(jugador);
        rankings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Historial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEsp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
