/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        this.setSize(493, 347);
        this.setLocationRelativeTo(null);
        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
    }

    public void actualizarInterfazIdioma() {
        if (Idioma.isEspanol()) {
            backEsp.setVisible(true);
            back.setVisible(false);
            done.setVisible(false);
            doneEsp.setVisible(true);
            jLabel1.setVisible(false);
            jLabelEsp.setVisible(true);
        } else {
            back.setVisible(true);
            backEsp.setVisible(false);
            done.setVisible(true);
            doneEsp.setVisible(false);
            jLabel1.setVisible(true);
            jLabelEsp.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasena = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        done = new javax.swing.JButton();
        doneEsp = new javax.swing.JButton();
        backEsp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEsp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(contrasena);
        contrasena.setBounds(150, 220, 180, 22);
        getContentPane().add(username);
        username.setBounds(150, 130, 180, 22);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(250, 260, 90, 30);

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/7.png"))); // NOI18N
        done.addActionListener(this::doneActionPerformed);
        getContentPane().add(done);
        done.setBounds(140, 260, 90, 30);

        doneEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/esp4.png"))); // NOI18N
        doneEsp.addActionListener(this::doneEspActionPerformed);
        getContentPane().add(doneEsp);
        doneEsp.setBounds(140, 260, 90, 30);

        backEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11esp.png"))); // NOI18N
        backEsp.addActionListener(this::backEspActionPerformed);
        getContentPane().add(backEsp);
        backEsp.setBounds(250, 260, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 310);

        jLabelEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/userpass.png"))); // NOI18N
        getContentPane().add(jLabelEsp);
        jLabelEsp.setBounds(0, 0, 480, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void procesarLogin()
    {
        String usuario = username.getText().trim();
        String password = contrasena.getText().trim();

        if (usuario.isEmpty() || password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos de la caja!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PersistenciaJugador persistencia = new PersistenciaJugador();

        if (!persistencia.existeJugador(usuario))
        {
            new CuentaNoExiste().setVisible(true);
            return;
        }

        Jugador jugador = persistencia.cargarJugador(usuario);

        if (!jugador.getContraseña().equals(password))
        {
            new IncorrectPass().setVisible(true);
            return;
        }
        jugador.setVidas(3);
        jugador.setActivo(true);
        UsuarioGuardado mensaje = new UsuarioGuardado(jugador);
        mensaje.setVisible(true);
        
        this.dispose();
//
//        Niveles ventanaNiveles = new Niveles(jugador);
//        ventanaNiveles.setVisible(true);
    }
    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
//
//        String usuario = username.getText().trim();
//        String password = contrasena.getText().trim();
//
//        if (usuario.isEmpty() || password.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos de la caja!", "Error", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        else {
//            UsuarioGuardado mensaje = new UsuarioGuardado();
//            mensaje.setVisible(true);
//        }
//
//        //temporal
//        System.out.println(username.getText());
//        System.out.println(contrasena.getText());
//        PersistenciaJugador persistencia = new PersistenciaJugador();
//
//        if (!persistencia.existeJugador(usuario)) {
//
//            new CuentaNoExiste().setVisible(true);
//            return;
//        }
//        Jugador jugador = persistencia.cargarJugador(usuario);
//        if (jugador.getContraseña().equals(password) == false) {
//            new IncorrectPass().setVisible(true);
//            return;
//        }
//        this.dispose();
//        Niveles ventana = new Niveles(jugador);
//        ventana.setLanzador(AppContext.getLanzador());
//        ventana.setVisible(true);
        procesarLogin();
    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        InicioJuego inicio = new InicioJuego();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void backEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEspActionPerformed
        // TODO add your handling code here:
        InicioJuego inicio = new InicioJuego();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_backEspActionPerformed

    private void doneEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEspActionPerformed
        // TODO add your handling code here:

//        String usuario = username.getText().trim();
//        String password = contrasena.getText().trim();
//
//        if (usuario.isEmpty() || password.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos de la caja!", "Error", JOptionPane.WARNING_MESSAGE);
//            return;
//        } else {
//            UsuarioGuardado mensaje = new UsuarioGuardado();
//            mensaje.setVisible(true);
//        }
//
//        //temporal
//        System.out.println(username.getText());
//        System.out.println(contrasena.getText());
//        PersistenciaJugador persistencia = new PersistenciaJugador();
//
//        if (!persistencia.existeJugador(usuario)) {
//
//            new CuentaNoExiste().setVisible(true);
//            return;
//        }
//        Jugador jugador = persistencia.cargarJugador(usuario);
//        if (jugador.getContraseña().equals(password) == false) {
//            new IncorrectPass().setVisible(true);
//            return;
//        }
//        this.dispose();
//        Niveles ventana = new Niveles(jugador);
//        ventana.setLanzador(AppContext.getLanzador());
//        ventana.setVisible(true);
        procesarLogin();
    }//GEN-LAST:event_doneEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backEsp;
    private javax.swing.JTextField contrasena;
    private javax.swing.JButton done;
    private javax.swing.JButton doneEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEsp;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
