/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class Niveles extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Niveles.class.getName());

    /**
     * Creates new form Niveles
     */
    public Niveles() {
        initComponents();
        
        this.setSize(450, 470);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivel1 = new javax.swing.JButton();
        nivel2 = new javax.swing.JButton();
        nivel3 = new javax.swing.JButton();
        nivel4 = new javax.swing.JButton();
        nivel5 = new javax.swing.JButton();
        nivel6 = new javax.swing.JButton();
        nivel7 = new javax.swing.JButton();
        nivel8 = new javax.swing.JButton();
        nivel9 = new javax.swing.JButton();
        nivel10 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nivel1);
        nivel1.setBounds(360, 90, 50, 50);
        getContentPane().add(nivel2);
        nivel2.setBounds(40, 90, 50, 50);
        getContentPane().add(nivel3);
        nivel3.setBounds(120, 90, 50, 50);
        getContentPane().add(nivel4);
        nivel4.setBounds(200, 90, 50, 50);
        getContentPane().add(nivel5);
        nivel5.setBounds(40, 180, 50, 50);
        getContentPane().add(nivel6);
        nivel6.setBounds(120, 180, 50, 50);
        getContentPane().add(nivel7);
        nivel7.setBounds(200, 180, 50, 50);
        getContentPane().add(nivel8);
        nivel8.setBounds(280, 180, 50, 50);
        getContentPane().add(nivel9);
        nivel9.setBounds(360, 180, 50, 50);
        getContentPane().add(nivel10);
        nivel10.setBounds(280, 90, 50, 50);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(140, 280, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/niveles.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 459, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Niveles().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nivel1;
    private javax.swing.JButton nivel10;
    private javax.swing.JButton nivel2;
    private javax.swing.JButton nivel3;
    private javax.swing.JButton nivel4;
    private javax.swing.JButton nivel5;
    private javax.swing.JButton nivel6;
    private javax.swing.JButton nivel7;
    private javax.swing.JButton nivel8;
    private javax.swing.JButton nivel9;
    // End of variables declaration//GEN-END:variables
}
