/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class Options extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Options.class.getName());

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
        
        this.setSize(493, 347);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        done = new javax.swing.JButton();
        volumen = new javax.swing.JButton();
        language1 = new javax.swing.JButton();
        musica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/7.png"))); // NOI18N
        done.addActionListener(this::doneActionPerformed);
        getContentPane().add(done);
        done.setBounds(190, 240, 90, 30);

        volumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/6.png"))); // NOI18N
        volumen.addActionListener(this::volumenActionPerformed);
        getContentPane().add(volumen);
        volumen.setBounds(250, 90, 70, 40);

        language1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/4.png"))); // NOI18N
        language1.addActionListener(this::language1ActionPerformed);
        getContentPane().add(language1);
        language1.setBounds(160, 150, 160, 60);

        musica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/5.png"))); // NOI18N
        musica.addActionListener(this::musicaActionPerformed);
        getContentPane().add(musica);
        musica.setBounds(160, 90, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/options.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 480, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumenActionPerformed

    private void language1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_language1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_language1ActionPerformed

    private void musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicaActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        InicioJuego inicio = new InicioJuego();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Options().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton language1;
    private javax.swing.JButton musica;
    private javax.swing.JButton volumen;
    // End of variables declaration//GEN-END:variables
}
