/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class Pausado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pausado.class.getName());
    private Jugador jugador;
    /**
     * Creates new form Pausado
     */
    public Pausado() {
        this.toFront();
        initComponents();
        this.setSize(493, 347);
        this.setLocationRelativeTo(null);
        actualizarInterfazIdioma();
        Idioma.suscribir(() -> actualizarInterfazIdioma());
    }

    public void actualizarInterfazIdioma() {
        if (Idioma.isEspanol()) {
            jLabel1.setVisible(false);
            jLabelEsp.setVisible(true);
        } else {
            jLabel1.setVisible(true);
            jLabelEsp.setVisible(false);
        }
    }
    public Pausado(Jugador jugador) {
        this.toFront();
        initComponents();
        this.setSize(493, 347);
        this.setLocationRelativeTo(null);
        this.jugador=jugador;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resume = new javax.swing.JButton();
        niveles = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEsp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/resume.png"))); // NOI18N
        resume.addActionListener(this::resumeActionPerformed);
        getContentPane().add(resume);
        resume.setBounds(210, 220, 120, 40);

        niveles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/10.png"))); // NOI18N
        niveles.addActionListener(this::nivelesActionPerformed);
        getContentPane().add(niveles);
        niveles.setBounds(130, 220, 60, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/pausado.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 310);

        jLabelEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/pausa.png"))); // NOI18N
        getContentPane().add(jLabelEsp);
        jLabelEsp.setBounds(0, 0, 480, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Niveles niveles = new Niveles(jugador);
        niveles.setVisible(true);
    }//GEN-LAST:event_nivelesActionPerformed

    private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_resumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pausado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEsp;
    private javax.swing.JButton niveles;
    private javax.swing.JButton resume;
    // End of variables declaration//GEN-END:variables
}
