/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author admin
 */
public class RankingsGlobales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RankingsGlobales.class.getName());

    /**
     * Creates new form Rankings
     */
    public RankingsGlobales() {
        initComponents();
        
        this.setSize(690, 500);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total = new javax.swing.JLabel();
        nivelesCompletados = new javax.swing.JLabel();
        vecesJugado = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        back = new javax.swing.JButton();
        backEsp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        total.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("####");
        getContentPane().add(total);
        total.setBounds(390, 380, 150, 40);

        nivelesCompletados.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        nivelesCompletados.setForeground(new java.awt.Color(255, 255, 255));
        nivelesCompletados.setText("####");
        getContentPane().add(nivelesCompletados);
        nivelesCompletados.setBounds(390, 320, 150, 40);

        vecesJugado.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        vecesJugado.setForeground(new java.awt.Color(255, 255, 255));
        vecesJugado.setText("####");
        getContentPane().add(vecesJugado);
        vecesJugado.setBounds(390, 260, 150, 40);

        rank.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        rank.setForeground(new java.awt.Color(255, 255, 255));
        rank.setText("####");
        getContentPane().add(rank);
        rank.setBounds(460, 140, 150, 40);

        jScrollPane1.setBackground(new java.awt.Color(190, 151, 123));

        jList1.setBackground(new java.awt.Color(220, 179, 152));
        jList1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 100, 150, 350);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/back.png"))); // NOI18N
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(570, 420, 90, 30);

        backEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/11esp.png"))); // NOI18N
        backEsp.addActionListener(this::backEspActionPerformed);
        getContentPane().add(backEsp);
        backEsp.setBounds(570, 420, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/global.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 676, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    }//GEN-LAST:event_backActionPerformed

    private void backEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RankingsGlobales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nivelesCompletados;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel total;
    private javax.swing.JLabel vecesJugado;
    // End of variables declaration//GEN-END:variables
}
